### ISSUE TITLE
Can we make a function that use pan, tilt and zoom?

### ISSUE THREAD

**Issue by Dream4Theater** [xMRi/PTZControl#1]
Can we make a function that takes x value ,y value and zoom value and goes there like preset or preset works different all from that ?

**Comment by xMRi** [comment]
The Zoom functionality is based on an internal property in the Logitech interface.
The Pan Tilt control doesn't allow any control via x/y coordinates. It only support motor on/off for the x/y direction.
I tried to use the given parameters for that in the Windows Driver Kit, but the Logitech PTZ 2 didn't support it.

**Comment by Dream4Theater** [comment]
I wanted move the camera where i clicked the screen. But what u said maked that impossible i guess. I think all i can do is go near of selected part.
https://support.digital-watchdog.com/kb/article/187-ptz-auto-focus-and-camera-control-in-dw-spectrum/
like this example when mouse select or drag go there but i guess thats impossible

**Comment by xMRi** [comment]
This is not possible with the available controls for the Logitech cameras. It may be possible for others. 
But you need to use another properties than used here in my code.

**Comment by Dream4Theater** [comment]
Thank you for your answers, helped a lot. I try to make my own library that i can get all functions but quite challenging when i dont quite expert on c++ but any way even this way program realy helped me a lot.

**Comment by Dream4Theater** [comment]
This can be a stupid question but can you give an idea about how i can make a library about control functions. Like when i call pan function, camera will pan that way or any hint how i can move because i lost in your code. Thank you for your support by the way
