### ISSUE TITLE
Preset name

### ISSUE THREAD

**Issue by tomazi78** [xMRi/PTZControl#11]
Is it possible to enter a form to freely name each preset?  I'm only interested in 4 such forms.  They can even be very short, just a few letters.

**Comment by xMRi** [comment]
Currently the presets are digits as graphics... 
You have tooltips. Didi you know that?

**Comment by tomazi78** [comment]
Yes I know about it. I thought that these names could be shown on the main window of the application. Surely the main window would have to be a bit bigger to fit everything. Unfortunately, I don't know how to program. I'd love to help, but it's black magic to me.

**Comment by tomazi78** [comment]
I also have a huge request for you. Since you own a LOGITECH PTZ camera, maybe you'd like to help me out. I care a lot about it. The socket in the camera is a standard PS2 plug. I don't have the original cable and need to know which plug pins the 12V (+/-) is connected to.
If you would like to help, please tell me which pins are connected to 12V (+/-). Here is a description of the plugin: https://www.engineersgarage.com/how-to-interface-a-ps2-keyboard-with-arduino-part-40-49/ (Figure No. 7)

Is pin 4 getting 5V from the USB-A plug?

**Comment by xMRi** [comment]
My church owns two cameras, but I have no idea how the cords pins are coded. 
But I saw enough cables on ebay.

**Comment by xMRi** [comment]
I see no way to add text to the buttons. Tooltips must be sufficient.
