### ISSUE TITLE
Selfish Request

### ISSUE THREAD

**Issue by Dthornt9** [xMRi/PTZControl#14]
I am forever grateful for the 3rd camera addition, is it possible to add support for a 4th?

**Comment by xMRi** [comment]
I think you should create your own fork of the problem. Shouldn't be so complicated to add a 4th camera.
The UI and order of the buttons may be the complicated.

But for my version I think it is sufficient to support 3 cameras. And even this is a lot.
May be it is easier to work with a 4th camera that is fixed to a position...
