### ISSUE TITLE
Cant Compile in VS Community 2022

### ISSUE THREAD

**Issue by kenglaze** [xMRi/PTZControl#16]
As the title states it failed to compile in VS Community 2022 with the following output shown below.
I apologies profusely if this is not the place to report this.  Also I am new to VS on windows so I might just be doing something dumb.
Any advice is welcome!  Maybe this code was meant for Linux with cmake or something?  

Build started...
1>------ Build started: Project: PTZControl, Configuration: Debug x64 ------
1>pch.cpp
1>ExtensionUnit.cpp
1>PTZControl.cpp
1>PTZControlDlg.cpp
1>C:\Users\kengl\source\repos\PTZControl\PTZControl\PTZControlDlg.cpp(438,9): error C2664: 'LRESULT SendMessageTimeoutW(HWND,UINT,WPARAM,LPARAM,UINT,UINT,PDWORD_PTR)': cannot convert argument 7 from 'DWORD *' to 'PDWORD_PTR'
1>C:\Users\kengl\source\repos\PTZControl\PTZControl\PTZControlDlg.cpp(438,102): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\winuser.h(3758,1): message : see declaration of 'SendMessageTimeoutW'
1>C:\Users\kengl\source\repos\PTZControl\PTZControl\PTZControlDlg.cpp(438,9): message : while trying to match the argument list '(HWND, int, int, int, int, int, DWORD *)'
1>SettingsDlg.cpp
1>Generating Code...
1>Done building project "PTZControl.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 10:50 PM and took 08.599 seconds ==========

**Comment by xMRi** [comment]
Strange. I used VS-2019 for this.
The code only works for Windows. It was never intended for anything else.

Change line 436 to 
`DWORD_PTR dwResult = 0;	`

**Comment by xMRi** [comment]
I just compiled my code with VS-2022 and didn't get such an error. 
You get this error only in the 64bit version. 

I would recommend to use the program only as 32bit program,

**Comment by xMRi** [comment]
Should be fixed
