### ISSUE TITLE
Mac or Linux version?

### ISSUE THREAD

**Issue by jojo2203** [xMRi/PTZControl#17]
Is an implementation for Mac os or Linux known or planned?

Thank you.

**Comment by xMRi** [comment]
Sorry. This is not planned, and handling USB stuff on Linux and Mac is totally different. Also I have no experiences here.

**Comment by jojo2203** [comment]
Danke für Ihre Nachricht. Auch wenn es schade ist.

 

MfG jojo

 
 

Gesendet: Montag, 06. November 2023 um 16:44 Uhr
Von: "Martin Richter" ***@***.***>
An: "xMRi/PTZControl" ***@***.***>
Cc: "jojo2203" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [xMRi/PTZControl] Mac or Linux version? (Issue #17)


 

Sorry. This is not planned, and handling USB stuff on Linux and Mac is totally different. Also I have no experiences here.
