### ISSUE TITLE
pan when holding button it goes wrong way

### ISSUE THREAD

**Issue by Dream4Theater** [xMRi/PTZControl#2]
when i hold the button on program it goes wrong way. when i hold on keyboard it goes on right way but it was slower and act like in a loop that getting turn pan function constantly. it is okay on push but when holding it pan function it goes wrong direction

**Comment by xMRi** [comment]
I can't repro this issue.
Everything works as it should with my 2 cameras.

Also the accelerator binding is correct. VK_LEFT triggers IDC_BT_LEFT and VK_RIGHT triggers IDC_BT_RIGHT.
