### ISSUE TITLE
add support for ConferenceCam CC3000e Camera?

### ISSUE THREAD

**Issue by borealis99** [xMRi/PTZControl#7]
Hi, adding this issue to see about support for the ConferenceCam CC3000e Camera, a predecessor to the PTZ Pro. It uses the same UVC controls, and it the device name in Windows is `ConferenceCam CC3000e Camera`
Thanks!

**Comment by xMRi** [comment]
I will add the camera name. Until the camera is automatically detected you can simply use the command line parameter.

**Comment by xMRi** [comment]
Done.
