### ISSUE TITLE
Control 3 camera

### ISSUE THREAD

**Issue by PH-MXRadio** [xMRi/PTZControl#8]
We have 3 camera on our radio studio is that possible to extend the software to 3 camera?

**Comment by xMRi** [comment]
Possible. 
But the UI need some rework for that. 
I try when I have some time

**Comment by PH-MXRadio** [comment]
That’s a good news, if i can help!

**Comment by xMRi** [comment]
The new version 2.3.0.40 now supports 3 cameras.
